using MetriplecticRelaxation
using MetriplecticRelaxation: integrate, energy, entropy
using MetriplecticRelaxation: SECTION5_RUNS, SECTION5_ORDER, EulerSquare, euler_flow,
                              state_extrema
using GeometricBrackets: project, vectorfield, gradient, entropy_gradient, issymmetric,
                         ispositive_semidefinite, degeneracy_residual, CollisionBracket,
                         MetriplecticFlow, QuadraticHamiltonian, entropy_production,
                         metric_matrix, metric_apply, field
using LinearAlgebra
using Random
using SparseArrays
using Test

# The runs here excite fields with random degrees of freedom, which is deliberate: a
# conservation or degeneracy identity tested on a single smooth mode reports round-off and hides
# a structural defect entirely. The seed is fixed so that a failure is reproducible.
Random.seed!(0x5c1e9a3b)

# Every resolution below is deliberately far coarser than a Section 4 run, and every final time
# far shorter. These tests assert the STRUCTURAL claims -- conservation, monotonicity,
# degeneracy, the closed forms -- which hold on any mesh. The claims that need resolution to be
# true at all, the rates and the contour averages, are the run drivers' business and are
# measured in `scripts/`, not here.
@testset "$(rpad("Collision Bracket Tests", 80))" begin
    @testset "$(rpad("Every run's bracket IS symmetric, PSD and DEGENERATE", 76))" begin
        for name in SECTION5_ORDER
            spec = SECTION5_RUNS[name]
            # Each run's own space, because that is part of the run.
            sq = EulerSquare(10, 2; state = spec.state)
            # Positive at every quadrature node, so B3's mobility M = ω is admissible, and not
            # an eigenmode, so the vector field is not accidentally zero. The constant offset
            # keeps it away from zero at the boundary and survives only in the free space.
            ω̂ = project(sq.space,
                x -> sin(π * x[1]) * sin(π * x[2]) *
                     (1.5 + 0.4sin(2π * x[1]) - 0.3cos(π * x[2])) +
                     (spec.state === :free ? 0.4 : 0.0))
            @test state_extrema(sq, ω̂)[1] > 0
            f = euler_flow(sq, spec)
            @test issymmetric(f.metric, ω̂)
            @test ispositive_semidefinite(f.metric, ω̂)
            # The flow's form, not the bracket's: the bracket supplies its own generator and is
            # clean by construction even when it is degenerate on the wrong energy.
            @test degeneracy_residual(f, ω̂) < 1e-11
            v = vectorfield(f, ω̂)
            @test abs(dot(gradient(f, ω̂), v)) / (norm(gradient(f, ω̂)) * norm(v)) < 1e-11
            @test dot(entropy_gradient(f, ω̂), v) < 0
            @test entropy_production(f, ω̂) > 0
            @test entropy_production(f, ω̂)≈-dot(entropy_gradient(f, ω̂), v) rtol=1e-12
            # Two independent evaluations of the same operator: the 𝔽_s moments against the
            # R/S/T factorisation.
            c = Vector(sq.M * ω̂)
            @test metric_apply(f.metric, ω̂, c)≈metric_matrix(f.metric, ω̂) * c rtol=1e-10
        end
    end

    sq = EulerSquare(10, 2)
    ω̂ = project(sq.space,
        x -> sin(π * x[1]) * sin(π * x[2]) * (1.5 + 0.4sin(2π * x[1]) - 0.3cos(π * x[2])))

    @testset "$(rpad("A MISMATCHED generator breaks the flow's degeneracy", 76))" begin
        # The trap `MetriplecticFlow` documents: a bracket generated by a different elliptic
        # problem is a perfectly good metric bracket, degenerate on the wrong energy.
        # A prescribed field unrelated to φ, not another elliptic solve: (K+M)⁻¹M gives a
        # stream function 0.95 φ, and degeneracy sees only direction.
        ĥ = project(sq.space, x -> sin(2π * x[1]) * sin(3π * x[2]))
        G = CollisionBracket(sq.space, ĥ)
        fw = MetriplecticFlow(sq.space, G, QuadraticHamiltonian(sq.MΛ),
            QuadraticHamiltonian(Matrix(sq.M)))
        @test degeneracy_residual(G, ω̂) < 1e-11
        # The ratio, not an absolute floor: `degeneracy_residual` normalises by max|𝔾| max|g|,
        # which bounds one product rather than the N-term sum, so a complete misalignment
        # normalises to 1e-3 -- thirteen orders above the clean value, and that is the gap.
        @test degeneracy_residual(fw, ω̂) > 1e8 * degeneracy_residual(G, ω̂)
    end

    @testset "$(rpad("An INDEFINITE mobility loses positivity and nothing else", 76))" begin
        # eq:M-condition requires M > 0. A mobility that changes sign keeps the symmetry and
        # the degeneracy, which is why positivity is a separate assertion.
        #
        # x₁ - 0.3, not x₁ - 0.5: the latter integrates to zero over the square, so the
        # bracket's moment m₀ = ∫M dμ vanishes and its recentring divides by it -- which
        # destroys the degeneracy too, for a reason that has nothing to do with the sign.
        Gi = CollisionBracket(sq.space, sq.Λ; mobility = (x, u) -> x[1] - 0.3,
            mobility_derivative = 0)
        @test !ispositive_semidefinite(Gi, ω̂)
        @test issymmetric(Gi, ω̂)
        @test degeneracy_residual(Gi, ω̂) < 1e-11
    end
end
